project_name: "NombreDeTuProyecto"
user_name: "TuNombre"
communication_language: "Spanish"
document_output_language: "Spanish"
user_skill_level: "expert"
output_folder: "{project-root}/_bmad-output"
planning_artifacts: "{project-root}/_bmad-output/planning-artifacts"
implementation_artifacts: "{project-root}/_bmad-output/implementation-artifacts"
project_knowledge: "{project-root}/docs/project"